### ISSUE TITLE
analyze-submission: submission 5cd588a4d96dad00085634a2 generates error

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/dcp-diag#20]
```
analyze-submission -d prod 5cd588a4d96dad00085634a2
Using deployment: prod

PHASE 1: Get submission primary bundle list from Ingest:
    Retrieving submission...done.
    Submission ID: 5cd588a4d96dad00085634a2
    Project UUID: cddab57b-6868-4be4-806f-395ed9dd635a
    Retrieving submission's primary bundle list...done.
    Ingest created 2544 bundles.

PHASE 2: Checking bundles are present in DSS:
    Checking for bundle manifests: AWS: 2544/2544 GCP: 2544/2544...done.
    2544 bundle are present in AWS
    2544 bundle are present in GCP

PHASE 3: Check DSS for primary bundles with this project UUID:
    Searching DSS...Traceback (most recent call last):
  File "/anaconda3/envs/hca/bin/analyze-submission", line 677, in <module>
    AnalyzeSubmission()
  File "/anaconda3/envs/hca/bin/analyze-submission", line 601, in __init__
    checker3.check()
  File "/anaconda3/envs/hca/bin/analyze-submission", line 253, in check
    bundle_info = self.state.bundle_map[bundle_uuid]
KeyError: 'ffb7d0c4-ae5a-4603-a669-f335584563a3'
```

**Comment by sampierson** [comment]
Updated `analyze-submission` to capture extra bundles returned from the DSS project UUID search, released version 1.1.0.

**Comment by sampierson** [comment]
@malloryfreeberg guessed these "extra" bundles were analysis bundles, and indeed the bundle counts match exactly:
```
PHASE 3: Check DSS for primary bundles with this project UUID:
	In AWS DSS, 2484 extra bundles are associated with this project
	In GCP DSS, 2479 extra bundles are associated with this project

PHASE 5: Check DSS for secondary bundles:
	In AWS there are 2484 primary bundles with 1 results bundles
	In GCP there are 2479 primary bundles with 1 results bundles
```

So, either our search that only returns primary bundles needs to be updated, or these secondary bundles don't have the metadata condition matching that search.

**Comment by sampierson** [comment]
@zperova says "we have replaced `process_type` with `type` in the analysis_process schema"

I updated the primary bundle search:
```
                        "must_not": [
                            {
                                "match": {
                                    "files.analysis_process_json.type.text": "analysis"
                                }
                            }
                        ]
```
