### ISSUE TITLE
Can't see a bundle with analyse-submission tool when it is visible in Swagger API

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/dcp-diag#21]
When i run dcp-diag to see the manually created imaging bundle I do not see it: 
```
(hca) C02X488AJHD2:Git zina$ analyze-submission -d staging 5d3036765f9ee90008d3e7cc --fresh
Using deployment: staging

PHASE 1: Get submission primary bundle list from Ingest:
	Retrieving submission...done.
	Submission ID: 5d3036765f9ee90008d3e7cc
	Project UUID: 80e70232-1f84-479d-8e59-87e85c616432
	Retrieving submission's primary bundle list...done.
	Ingest created 0 bundles.
	Saving state in 5d3036765f9ee90008d3e7cc.json...done.

PHASE 2: Checking bundles are present in DSS:
	Checking for bundle manifests:...done.
	0 bundle are present in AWS
	0 bundle are present in GCP
	Saving state in 5d3036765f9ee90008d3e7cc.json...done.

PHASE 3: Check DSS for primary bundles with this project UUID:
	Searching DSS...done.
	In AWS DSS, 0 primary bundles are indexed by project
	In AWS DSS, 2 extra bundles are associated with this project
	In GCP DSS, 0 primary bundles are indexed by project
	Saving state in 5d3036765f9ee90008d3e7cc.json...done.

PHASE 4: No auth information provided, skip checking Secondary Analysis for workflows.

PHASE 5: Check DSS for secondary bundles:
	Searching for secondary bundles: ...done.
	Saving state in 5d3036765f9ee90008d3e7cc.json...done.

PHASE 6: Check Azul for primary bundles:
	Counting bundles in webservice...Traceback (most recent call last):
  File "/anaconda3/envs/hca/bin/analyze-submission", line 747, in <module>
    AnalyzeSubmission()
  File "/anaconda3/envs/hca/bin/analyze-submission", line 717, in __init__
    checker6.check()
  File "/anaconda3/envs/hca/bin/analyze-submission", line 569, in check
    project_bundle_fqids = agent.get_project_bundle_fqids(self.state.project_uuid)
  File "/anaconda3/envs/hca/lib/python3.6/site-packages/dcp_diag/component_agents/azul_agent.py", line 32, in get_project_bundle_fqids
    search_after = response_json['pagination']['search_after']
KeyError: 'pagination'
```

However, it is discoverable when using Swagger API:

![Screenshot 2019-08-19 at 11 22 46](https://user-images.githubusercontent.com/38244059/63258330-b67a3280-c273-11e9-894b-34a7c9372807.png)

**Comment by sampierson** [comment]
Which swagger API?  The Azul one?

**Comment by sampierson** [comment]
Can you cut and paste the URL for that query?

**Comment by sampierson** [comment]
@GPelayo ping

**Comment by sampierson** [comment]
FYI I fixed the exception with dcp-diag version 1.2.0 but there may be another issue here worth investigating.

**Comment by zperova** [comment]
i am trying to find this bundle's uuid

**Comment by zperova** [comment]
OK, so here is what I did. I went to staging Swagger API and searched for the bundles by project uuid: 
```
{
  "es_query": {
    "query": {
      "match": {
        "files.project_json.provenance.document_id": "80e70232-1f84-479d-8e59-87e85c616432"
      }
    }
  }
}
```
and got the following response: 
``` 
{
  "es_query": {
    "query": {
      "match": {
        "files.project_json.provenance.document_id": "80e70232-1f84-479d-8e59-87e85c616432"
      }
    }
  },
  "results": [
    {
      "bundle_fqid": "ed8dfc49-2984-4b14-b40d-03a4e51c27eb.2019-07-18T091611.931866Z",
      "bundle_url": "https://dss.staging.data.humancellatlas.org/v1/bundles/ed8dfc49-2984-4b14-b40d-03a4e51c27eb?version=2019-07-18T091611.931866Z&replica=aws",
      "search_score": null
    },
    {
      "bundle_fqid": "7a8123db-6ba7-43a6-9b96-e26f99b77601.2019-08-02T165239.001000Z",
      "bundle_url": "https://dss.staging.data.humancellatlas.org/v1/bundles/7a8123db-6ba7-43a6-9b96-e26f99b77601?version=2019-08-02T165239.001000Z&replica=aws",
      "search_score": null
    }
  ],
  "total_hits": 2
}
```

**Comment by zperova** [comment]
there are actually 2 bundles as I understand. Before I only had 1 fqid, and I do not remember which one.

**Comment by zperova** [comment]
And of course now I found the fqid of the bundle that i was given initially: 7a8123db-6ba7-43a6-9b96-e26f99b77601
ANd here is the ticket if you are interested in some background: https://github.com/HumanCellAtlas/ingest-central/issues/491

**Comment by GPelayo** [comment]
Looks like the agent is using make an API call with an outdated filter query to retrieve the bundle info from Azul. I can see this API call here. https://github.com/HumanCellAtlas/dcp-diag/blob/3c5d52c62b5ee7d06e2bf61948b4d20224c149d3/dcp_diag/component_agents/azul_agent.py#L13-L19
I'll update the above code and test the analyse-submission tool if this is the case.

**Comment by zperova** [comment]
@GPelayo is there any update on this issue?

**Comment by GPelayo** [comment]
I made a made some code changes awhile ago that should resolve this issue, but it needs to be reviewed. @sampierson do you have time review my PR?

**Comment by sampierson** [comment]
@GPelayo done.  Apologies for the delay.  I only work part time, and every time I open my inbox there are about 150 messages from GitHub in it.  It's easy to miss these requests.  Ping me in Slack for faster response.

**Comment by GPelayo** [comment]
@zperova the newest release of dcp-diag should resolve this issue.

**Comment by sampierson** [comment]
@zperova please can you try `dcp-diag` version `1.3.0` and  "Close and comment" if the problem is resolved.

**Comment by theathorn** [comment]
No demo by @GPelayo required.

**Comment by theathorn** [comment]
@zperova Can this be closed now?

**Comment by zperova** [comment]
@samanehsan I have checked with the `dcp-diag 1.3.0` and i get the following:
```
(hca) C02X488AJHD2:~ zina$ analyze-submission -d staging 5d3036765f9ee90008d3e7cc --fresh
Using deployment: staging

PHASE 1: Get submission primary bundle list from Ingest:
	Retrieving submission...done.
	Submission ID: 5d3036765f9ee90008d3e7cc
	Project UUID: 80e70232-1f84-479d-8e59-87e85c616432
	Retrieving submission's primary bundle list...done.
	Ingest created 1 bundles.
	Saving state in 5d3036765f9ee90008d3e7cc.json...done.

PHASE 2: Checking bundles are present in DSS:
	Checking for bundle manifests: AWS: 1/1 GCP: 1/1...done.
	1 bundle are present in AWS
	0 bundle are present in GCP
	Saving state in 5d3036765f9ee90008d3e7cc.json...done.

PHASE 3: Check DSS for primary bundles with this project UUID:
	Searching DSS...done.
	In AWS DSS, 1 primary bundles are indexed by project
	In AWS DSS, 1 extra bundles are associated with this project
	In GCP DSS, 0 primary bundles are indexed by project
	In GCP DSS, 1 primary bundles are NOT indexed by project
	Saving state in 5d3036765f9ee90008d3e7cc.json...done.

PHASE 4: No auth information provided, skip checking Secondary Analysis for workflows.

PHASE 5: Check DSS for secondary bundles:
	Searching for secondary bundles: AWS: 1/1 GCP: 1/1...done.
	In AWS there are 1 primary bundles with 0 results bundles
	In GCP there are 1 primary bundles with 0 results bundles
	Saving state in 5d3036765f9ee90008d3e7cc.json...done.

PHASE 6: Check Azul for primary bundles:
	Counting bundles in webservice...done.
	In Azul, 0 primary bundles are indexed
	In Azul, 1 primary bundles are NOT indexed
	Saving state in 5d3036765f9ee90008d3e7cc.json...done.

PHASE 7: Check Azul for secondary bundles:
	Counting secondary bundles in webservice...done.
	In Azul there are 1 primary bundles with 0 results bundles
	Saving state in 5d3036765f9ee90008d3e7cc.json...done.
```

Which means that the tool now works but I can see further discrepancies between AWS and GCP, as well as that this bundle is not indexed by Azul. These questions are irrelevant here, I will open issues in the corresponding repos.

Closing this issue.
